[package]
name = "rust-web"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "2.0"
actix-rt = "1.0.0"
actix-service = "1.0.0"
serde = "1.0"
bytes = "0.5.2"
json = "*"
